
title: Sierra Moore
description: "front end web developer"
keywords: web developer, personal site, freelance web developer, front end web developer, front-end web developer

url: https://sierramoore.com
github_username:  sierramoore
email: sierra.v.moore@gmail.com
repository: https://github.com/sierramoore/personal_site_2
google_analytics: UA-122925196-1


exclude: [".idea/"]

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 10 versions

